/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleGlossaryRouteImport } from './routes/$locale/glossary'
import { Route as LocaleBrowseRouteImport } from './routes/$locale/browse'
import { Route as LocaleSplatRouteImport } from './routes/$locale/$'
import { Route as LocaleTopicsTopicRouteImport } from './routes/$locale/topics/$topic'
import { Route as LocaleRolesRoleRouteImport } from './routes/$locale/roles/$role'
import { Route as LocalePathsSlugRouteImport } from './routes/$locale/paths/$slug'
import { Route as LocaleLevelsLevelRouteImport } from './routes/$locale/levels/$level'
import { Route as LocaleArticlesSlugRouteImport } from './routes/$locale/articles/$slug'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleGlossaryRoute = LocaleGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBrowseRoute = LocaleBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleTopicsTopicRoute = LocaleTopicsTopicRouteImport.update({
  id: '/topics/$topic',
  path: '/topics/$topic',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleRolesRoleRoute = LocaleRolesRoleRouteImport.update({
  id: '/roles/$role',
  path: '/roles/$role',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePathsSlugRoute = LocalePathsSlugRouteImport.update({
  id: '/paths/$slug',
  path: '/paths/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleLevelsLevelRoute = LocaleLevelsLevelRouteImport.update({
  id: '/levels/$level',
  path: '/levels/$level',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleArticlesSlugRoute = LocaleArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/browse': typeof LocaleBrowseRoute
  '/$locale/glossary': typeof LocaleGlossaryRoute
  '/$locale/': typeof LocaleIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/levels/$level': typeof LocaleLevelsLevelRoute
  '/$locale/paths/$slug': typeof LocalePathsSlugRoute
  '/$locale/roles/$role': typeof LocaleRolesRoleRoute
  '/$locale/topics/$topic': typeof LocaleTopicsTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/browse': typeof LocaleBrowseRoute
  '/$locale/glossary': typeof LocaleGlossaryRoute
  '/$locale': typeof LocaleIndexRoute
  '/studio': typeof StudioIndexRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/levels/$level': typeof LocaleLevelsLevelRoute
  '/$locale/paths/$slug': typeof LocalePathsSlugRoute
  '/$locale/roles/$role': typeof LocaleRolesRoleRoute
  '/$locale/topics/$topic': typeof LocaleTopicsTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/browse': typeof LocaleBrowseRoute
  '/$locale/glossary': typeof LocaleGlossaryRoute
  '/$locale/': typeof LocaleIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/$locale/articles/$slug': typeof LocaleArticlesSlugRoute
  '/$locale/levels/$level': typeof LocaleLevelsLevelRoute
  '/$locale/paths/$slug': typeof LocalePathsSlugRoute
  '/$locale/roles/$role': typeof LocaleRolesRoleRoute
  '/$locale/topics/$topic': typeof LocaleTopicsTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/$'
    | '/$locale/browse'
    | '/$locale/glossary'
    | '/$locale/'
    | '/studio/'
    | '/$locale/articles/$slug'
    | '/$locale/levels/$level'
    | '/$locale/paths/$slug'
    | '/$locale/roles/$role'
    | '/$locale/topics/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/$'
    | '/$locale/browse'
    | '/$locale/glossary'
    | '/$locale'
    | '/studio'
    | '/$locale/articles/$slug'
    | '/$locale/levels/$level'
    | '/$locale/paths/$slug'
    | '/$locale/roles/$role'
    | '/$locale/topics/$topic'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/$'
    | '/$locale/browse'
    | '/$locale/glossary'
    | '/$locale/'
    | '/studio/'
    | '/$locale/articles/$slug'
    | '/$locale/levels/$level'
    | '/$locale/paths/$slug'
    | '/$locale/roles/$role'
    | '/$locale/topics/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/glossary': {
      id: '/$locale/glossary'
      path: '/glossary'
      fullPath: '/$locale/glossary'
      preLoaderRoute: typeof LocaleGlossaryRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/browse': {
      id: '/$locale/browse'
      path: '/browse'
      fullPath: '/$locale/browse'
      preLoaderRoute: typeof LocaleBrowseRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/topics/$topic': {
      id: '/$locale/topics/$topic'
      path: '/topics/$topic'
      fullPath: '/$locale/topics/$topic'
      preLoaderRoute: typeof LocaleTopicsTopicRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/roles/$role': {
      id: '/$locale/roles/$role'
      path: '/roles/$role'
      fullPath: '/$locale/roles/$role'
      preLoaderRoute: typeof LocaleRolesRoleRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/paths/$slug': {
      id: '/$locale/paths/$slug'
      path: '/paths/$slug'
      fullPath: '/$locale/paths/$slug'
      preLoaderRoute: typeof LocalePathsSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/levels/$level': {
      id: '/$locale/levels/$level'
      path: '/levels/$level'
      fullPath: '/$locale/levels/$level'
      preLoaderRoute: typeof LocaleLevelsLevelRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/articles/$slug': {
      id: '/$locale/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/$locale/articles/$slug'
      preLoaderRoute: typeof LocaleArticlesSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleSplatRoute: typeof LocaleSplatRoute
  LocaleBrowseRoute: typeof LocaleBrowseRoute
  LocaleGlossaryRoute: typeof LocaleGlossaryRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleArticlesSlugRoute: typeof LocaleArticlesSlugRoute
  LocaleLevelsLevelRoute: typeof LocaleLevelsLevelRoute
  LocalePathsSlugRoute: typeof LocalePathsSlugRoute
  LocaleRolesRoleRoute: typeof LocaleRolesRoleRoute
  LocaleTopicsTopicRoute: typeof LocaleTopicsTopicRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleSplatRoute: LocaleSplatRoute,
  LocaleBrowseRoute: LocaleBrowseRoute,
  LocaleGlossaryRoute: LocaleGlossaryRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleArticlesSlugRoute: LocaleArticlesSlugRoute,
  LocaleLevelsLevelRoute: LocaleLevelsLevelRoute,
  LocalePathsSlugRoute: LocalePathsSlugRoute,
  LocaleRolesRoleRoute: LocaleRolesRoleRoute,
  LocaleTopicsTopicRoute: LocaleTopicsTopicRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
